name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork with upstream
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: CVEProject
          base: main
          head: main
          token: ${{ secrets.GITHUB_TOKEN }}
